# Generated by Django 5.0 on 2024-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
